from __future__ import annotations

import argparse
import json

from .aws_clients import clients
from .config import GENERATED_ENV_FILE, load_config, utc_now, write_json

OUTPUT_TO_ENV = {
    "BucketName": "S3_BUCKET_NAME",
    "SageMakerExecutionRoleArn": "SAGEMAKER_EXECUTION_ROLE_ARN",
    "FraudDecisionTableName": "FRAUD_DECISION_TABLE_NAME",
    "FraudEventQueueUrl": "FRAUD_EVENT_QUEUE_URL",
    "FraudEventQueueName": "FRAUD_EVENT_QUEUE_NAME",
    "FraudS3Prefix": "FRAUD_S3_PREFIX",
}


def write_stack_outputs() -> dict[str, str]:
    config = load_config(require_aws=False)
    cf = clients(config).cloudformation
    response = cf.describe_stacks(StackName=config.stack_name)
    outputs = {
        output["OutputKey"]: output["OutputValue"]
        for output in response["Stacks"][0].get("Outputs", [])
    }
    parameters = {
        parameter["ParameterKey"]: parameter["ParameterValue"]
        for parameter in response["Stacks"][0].get("Parameters", [])
    }
    env_lines = [
        "# Generated by python -m src.fetch_stack_outputs. Do not commit account-specific values.",
        f"AWS_REGION={config.aws_region}",
    ]
    if config.aws_profile:
        env_lines.append(f"AWS_PROFILE={config.aws_profile}")
    if parameters.get("CreateBucket"):
        env_lines.append(f"CREATE_BUCKET={parameters['CreateBucket']}")
    for output_key, env_key in OUTPUT_TO_ENV.items():
        if outputs.get(output_key):
            env_lines.append(f"{env_key}={outputs[output_key]}")
    GENERATED_ENV_FILE.write_text("\n".join(env_lines) + "\n", encoding="utf-8")
    write_json(
        config.metadata_path("infra_outputs.json"),
        {
            "outputs": outputs,
            "parameters": parameters,
            "env_file": str(GENERATED_ENV_FILE),
            "written_at": utc_now(),
        },
    )
    print(f"Infrastructure outputs written to {GENERATED_ENV_FILE}")
    print(json.dumps(outputs, indent=2, sort_keys=True))
    return outputs


def main() -> None:
    argparse.ArgumentParser(description="Write CloudFormation outputs to .env.cloud.").parse_args()
    write_stack_outputs()


if __name__ == "__main__":
    main()
