"""Clean local files generated by the lab."""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

from .config import ROOT_DIR, load_config, write_metadata


def _resolve_under_root(path: Path) -> Path:
    resolved = (ROOT_DIR / path).resolve() if not path.is_absolute() else path.resolve()
    root = ROOT_DIR.resolve()
    if resolved != root and root not in resolved.parents:
        raise ValueError(f"Refusing to clean path outside lab root: {resolved}")
    return resolved


def _list_children(path: Path) -> list[Path]:
    if not path.exists():
        return []
    return sorted(path.iterdir(), key=lambda item: str(item).lower())


def _clean_directory_contents(path: Path, *, execute: bool) -> dict[str, object]:
    resolved = _resolve_under_root(path)
    children = _list_children(resolved)
    actions: list[dict[str, str]] = []
    for child in children:
        action = {"path": str(child), "status": "would_delete"}
        if execute:
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()
            action["status"] = "deleted"
        actions.append(action)
    if execute:
        resolved.mkdir(parents=True, exist_ok=True)
    return {
        "directory": str(resolved),
        "exists": resolved.exists(),
        "items": actions,
        "item_count": len(actions),
    }


def cleanup_local_outputs(execute: bool = False) -> dict[str, object]:
    config = load_config(validate=False)
    targets = [
        config.local_outputs_dir,
        config.local_cache_dir,
    ]
    payload = {
        "executed": execute,
        "safe_default": "Dry run only. Pass --execute to delete generated local lab files.",
        "scope": [
            "artifacts/local_outputs",
            "data/local_cache",
        ],
        "retained": [
            ".env and .env.cloud",
            "source code",
            "lab documentation",
            "S3 outputs",
        ],
        "targets": [_clean_directory_contents(target, execute=execute) for target in targets],
    }
    if not execute:
        write_metadata(config, "cleanup_local_outputs_plan", payload)
    return payload


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--execute", action="store_true")
    args = parser.parse_args()
    print(json.dumps(cleanup_local_outputs(execute=args.execute), indent=2, default=str))


if __name__ == "__main__":
    main()
