from __future__ import annotations

import argparse
from pathlib import Path
import shutil

from src.config import LOCAL_CACHE_DIR, LOCAL_OUTPUTS_DIR, SAMPLE_DATA_DIR


GENERATED_PATHS = (
    LOCAL_OUTPUTS_DIR,
    LOCAL_CACHE_DIR,
)

GENERATED_FILE_PATTERNS = (
    SAMPLE_DATA_DIR / "*.csv",
)


def _clean_directory(path: Path, dry_run: bool) -> None:
    if not path.exists():
        return
    for item in path.iterdir():
        if item.name == ".gitkeep":
            continue
        print(f"{'Would delete' if dry_run else 'Deleting'} {item}")
        if dry_run:
            continue
        if item.is_dir():
            shutil.rmtree(item)
        else:
            item.unlink()


def _clean_file_pattern(pattern: Path, dry_run: bool) -> None:
    parent = pattern.parent
    if not parent.exists():
        return
    for item in parent.glob(pattern.name):
        if item.name == ".gitkeep":
            continue
        print(f"{'Would delete' if dry_run else 'Deleting'} {item}")
        if not dry_run:
            item.unlink()


def clean_local_outputs(dry_run: bool = False) -> None:
    for path in GENERATED_PATHS:
        _clean_directory(path, dry_run)
    for pattern in GENERATED_FILE_PATTERNS:
        _clean_file_pattern(pattern, dry_run)


def main() -> None:
    parser = argparse.ArgumentParser(description="Delete local files generated by the lab without touching AWS.")
    parser.add_argument("--dry-run", action="store_true", help="Show files that would be deleted.")
    args = parser.parse_args()
    clean_local_outputs(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
