from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from src.config import GENERATED_ENV_FILE, PROJECT_ROOT


KEEP_NAMES = {".gitkeep"}


def assert_inside_project(path: Path) -> None:
    project_root = PROJECT_ROOT.resolve()
    resolved = path.resolve()
    try:
        resolved.relative_to(project_root)
    except ValueError as exc:
        raise ValueError(f"Refusing to remove path outside project: {resolved}") from exc


def remove_path(path: Path, dry_run: bool) -> bool:
    assert_inside_project(path)
    if not path.exists() and not path.is_symlink():
        return False
    print(f"{'Would remove' if dry_run else 'Removing'} {path.relative_to(PROJECT_ROOT)}")
    if dry_run:
        return True
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink()
    return True


def directory_contents(directory: Path) -> list[Path]:
    if not directory.exists():
        return []
    assert_inside_project(directory)
    return [path for path in directory.iterdir() if path.name not in KEEP_NAMES]


def generated_paths() -> list[Path]:
    paths: list[Path] = []
    paths.extend(directory_contents(PROJECT_ROOT / "artifacts" / "local_outputs"))
    paths.extend(directory_contents(PROJECT_ROOT / "data" / "local_cache"))
    sample_dir = PROJECT_ROOT / "data" / "sample"
    if sample_dir.exists():
        assert_inside_project(sample_dir)
        paths.extend(sample_dir.glob("*.csv"))
    paths.append(GENERATED_ENV_FILE)
    return paths


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Remove local files generated by the lab. AWS resources and .env are not deleted.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be removed without deleting files.",
    )
    args = parser.parse_args()

    removed = 0
    for path in generated_paths():
        if remove_path(path, args.dry_run):
            removed += 1

    action = "would be removed" if args.dry_run else "removed"
    print(f"Local cleanup complete: {removed} item(s) {action}.")
    print("AWS resources were not changed. The .env file was preserved.")


if __name__ == "__main__":
    main()
