from __future__ import annotations

import json
import logging

from src.aws_clients import client
from src.config import GENERATED_ENV_FILE, get_config
from src.logging_utils import configure_logging


LOGGER = logging.getLogger(__name__)


OUTPUT_TO_ENV = {
    "BucketName": "S3_BUCKET_NAME",
    "SageMakerExecutionRoleArn": "SAGEMAKER_EXECUTION_ROLE_ARN",
}


def write_stack_outputs(config) -> dict[str, str]:
    cf = client(config, "cloudformation")
    response = cf.describe_stacks(StackName=config.stack_name)
    outputs = {
        output["OutputKey"]: output["OutputValue"]
        for output in response["Stacks"][0].get("Outputs", [])
    }
    env_lines = [
        "# Generated by python -m src.fetch_stack_outputs. Do not commit account-specific values.",
    ]
    for output_key, env_key in OUTPUT_TO_ENV.items():
        if outputs.get(output_key):
            env_lines.append(f"{env_key}={outputs[output_key]}")
    GENERATED_ENV_FILE.write_text("\n".join(env_lines) + "\n", encoding="utf-8")
    output_path = config.local_outputs_dir / "infra_outputs.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(outputs, indent=2, sort_keys=True), encoding="utf-8")
    LOGGER.info("Wrote %s and %s", GENERATED_ENV_FILE, output_path)
    return outputs


def main() -> None:
    configure_logging()
    config = get_config()
    write_stack_outputs(config)


if __name__ == "__main__":
    main()
